[project]
name = "queueboard-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dateutil>=2.9.0.post0",
    "zulip>=0.9.0",
]

[dependency-groups]
dev = [
    "ruff>=0.13.1",
]
